[package]
name = "ggsand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
oorandom = "11.1.3"
glam = "0.22.0"